A basic docker wrapper around [[https://github.com/yt-dlp/yt-dlp][yt-dlp]], ffmpeg included.

* Build

Supported archs are =amd64= and =arm64= (the ffmpeg [[https://github.com/yt-dlp/FFmpeg-Builds][builds]] by yt-dlp team are
only that).

#+begin_example
  docker build -t yt-dlp .
#+end_example

* Usage

Download a video in the best quality into the current dir:

#+begin_src bash
  opts=(
      -it --rm --init
      -v "$PWD":/workdir
      -u $(id -u):$(id -g) -e HOME=/home/user
  )

  docker run "${opts[@]}" yt-dlp 'https://www.youtube.com/watch?v=sQFXKOPJOYM'
#+end_src

If you omit the =-u .. -e ..= piece, downloaded files would be owned by
=1000:1000=.

In the command above, after the image name you can use any yt-dlp options.

* yt-dlp.docker

Runner for the image with such features:

- auto detect your =$user_name= when run under sudo/doas
- mount =/home/$user_name/Downloads/yt-dlp= inside the container as the workdir
- set the output subdir to the current date
- prepend the output filename with the upload date

* yt-quick

A wrapper around =yt-dlp.docker= for youtube. It would download the H264 video
of up to the selected height (1080 if not set) along with the best AAC audio.

 #+begin_example
   Usage: yt-quick [1080|720|480|360] url1 url2 ..
 #+end_example
